(defpackage :swt-gen
  (:use :common-lisp :jfli))

(in-package :swt-gen)

(def-java-class "java.lang.System")
(def-java-class "java.net.URL")
(def-java-class "java.io.File")
(def-java-class "org.eclipse.jface.action.Action")
(def-java-class "org.eclipse.jface.action.MenuManager")
(def-java-class "org.eclipse.jface.resource.ImageRegistry")
(def-java-class "org.eclipse.jface.resource.ImageDescriptor")
(def-java-class "org.eclipse.jface.window.ApplicationWindow")
(def-java-class "org.eclipse.jface.window.Window")
(def-java-class "org.eclipse.swt.widgets.Display")
(def-java-class "org.eclipse.swt.widgets.Shell")
(def-java-class "org.eclipse.swt.widgets.Button")
(def-java-class "org.eclipse.swt.widgets.Table")
(def-java-class "org.eclipse.swt.widgets.TableColumn")
(def-java-class "org.eclipse.swt.SWT")
(def-java-class "org.eclipse.swt.custom.SashForm")
(def-java-class "org.eclipse.jface.viewers.TreeViewer")
(def-java-class "org.eclipse.jface.viewers.TableViewer")
(def-java-class "org.eclipse.jface.viewers.ViewerFilter")
(def-java-class "org.eclipse.jface.viewers.ViewerSorter")
(def-java-class "org.eclipse.jface.viewers.ITreeContentProvider")
(def-java-class "org.eclipse.jface.viewers.IStructuredContentProvider")
(def-java-class "org.eclipse.jface.viewers.ISelectionChangedListener")
(def-java-class "org.eclipse.jface.viewers.IStructuredSelection")
(def-java-class "org.eclipse.jface.viewers.ITableLabelProvider")
(def-java-class "org.eclipse.jface.viewers.ILabelProvider")
(def-java-class "org.eclipse.jface.viewers.SelectionChangedEvent")
(def-java-class "org.eclipse.swt.graphics.Image")


;;(def-java-class "org.armedbear.lisp.LispObject")